### ISSUE TITLE
Отключение логов

### ISSUE THREAD

**Issue by SashkaNik** [daswer123/silero-tts-enhanced#1]
Здравствуйте, можно ли как-то отключить вывод логов в консоль?

**Comment by daswer123** [comment]
Здравствуйте, пока нельзя.
Взял себе на заметку, реализую в ближайшее время.

**Comment by SashkaNik** [comment]
Хорошо, спасибо

**Comment by daswer123** [comment]
Привет, дошли руки до этой библиотеки, посмотри последний релиз 
https://github.com/daswer123/silero-tts-enhanced/releases/tag/0.0.5
